services:
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: mrlt8/wyze-bridge:latest
    ports:
      - "11935:1935" # RTMP
      - "18554:8554" # RTSP
      - "18888:8888" # HLS
      - "15000:5000" # API
    env_file:
      - .env
  
  vistterstudio:
    container_name: vistterstudio
    restart: unless-stopped
    build: ./server
    ports:
      - "18080:8080"
    volumes:
      - ./server/assets:/usr/src/app/assets
    depends_on:
      - wyze-bridge

  frontend:
    container_name: vistterstudio-frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - "19000:80"
    depends_on:
      - vistterstudio
