services:
  vistterstudio:
    container_name: vistterstudio
    restart: unless-stopped
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/assets:/usr/src/app/assets
    environment:
      - NODE_ENV=production
      - PORT=8080

  broadcast-server:
    container_name: vistterstudio-broadcast
    restart: unless-stopped
    build: ./broadcast-server
    ports:
      - "3001:3001"
    volumes:
      - ./broadcast-server/recordings:/usr/src/app/recordings
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      - vistterstudio

  frontend:
    container_name: vistterstudio-frontend
    restart: unless-stopped
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - vistterstudio
      - broadcast-server
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_BROADCAST_URL=http://localhost:3001
